version: "3.9"

services:
    api:
        build:
            context: .
            dockerfile: Dockerfile
            target: dev
        #env_file:
        #    - ./api/.env
        stop_signal: SIGINT
        environment:
            PORT: 8730
            APP_ENV: local
            SERVICE_NAME: abc-soup
            SERVICE_NAMESPACE: bai
        volumes:
            - api_0_pip:/root/.cache/pip
            - ./src:/app/src
            - ./shared-assets:/app/shared-assets
        ports:
            - "8730:8730"

volumes:
    api_0_pip:
