name: abc-suite CI

env:
    DOCKER_BUILDKIT: 1

on:
    push:
        branches: [ main, develop ]
        tags:
            - 'v[0-9]+.[0-9]+.[0-9]+'
            - '[0-9]+.[0-9]+.[0-9]+'
    pull_request:
        branches: [ main, develop ]

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
    publish_docker_api:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [ 18.x ]
        steps:
            -   uses: actions/checkout@v3
            -   name: Set Branch
                id: short_ref
                run: echo ::set-output name=short_ref::${GITHUB_REF#refs/*/}
            -   name: Set git_url_commit
                id: git_url_commit
                run: echo ::set-output name=git_url_commit::${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/commit/${GITHUB_SHA}
            -   name: Set git_url_ci_run
                id: git_url_ci_run
                run: echo ::set-output name=git_url_ci_run::${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}
            -   name: Set git_commit
                id: git_commit
                run: echo ::set-output name=git_commit::${GITHUB_REPOSITORY}/${GITHUB_SHA}
            -   name: Set git_ci_run
                id: git_ci_run
                run: echo ::set-output name=git_ci_run::${GITHUB_REPOSITORY}/${GITHUB_RUN_ID}

            -   name: Build image `api`
                run: |
                    docker image build -t abc-soup -f Dockerfile .
